version: '3.8'

services:
  mysql:
    image: mysql:8.0.36
    container_name: mysql-server
    environment:
      MYSQL_ROOT_PASSWORD: 1234
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql

  redis:
    image: redis:7.0.11
    container_name: redis-server
    ports:
      - "6379:6379"

  rabbitmq:
    image: rabbitmq:3.8.5-management
    container_name: rabbitmq-server
    environment:
      RABBITMQ_DEFAULT_USER: admin
      RABBITMQ_DEFAULT_PASS: adminpass
    ports:
      - "15672:15672"
      - "5672:5672"

volumes:
  mysql-data: